# Configuración Clever Cloud MySQL
spring.datasource.url=jdbc:mysql://bpp6yvghn0n46q5iic0t-mysql.services.clever-cloud.com:3306/bpp6yvghn0n46q5iic0t?useSSL=false&serverTimezone=UTC
spring.datasource.username=uy7jrkpt9csh77be
spring.datasource.password=TfXmP5D8q6n7SjNfE9rV

# Estrategia JPA para MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080
